# -*- coding: utf-8 -*-
"""PCB_YOLOv8_Colab - Mary Zeno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dPRhaQA9_2OyjPLqakETAYZ462IVlzHq
"""

!kaggle datasets list | head

from google.colab import drive
drive.mount('/content/drive')

!ls -R data/pcb/splits | head -n 60
!cat pcb.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/5804/Intro-to-AI-Project

# Create the missing folders (recursive)
!mkdir -p data/pcb/splits/images/train
!mkdir -p data/pcb/splits/images/val
!mkdir -p data/pcb/splits/images/test
!mkdir -p data/pcb/splits/labels/train
!mkdir -p data/pcb/splits/labels/val
!mkdir -p data/pcb/splits/labels/test

!python train_pcb_yolov8.py \
  --dataset norbertelter/pcb-defect-dataset \
  --data_root data/raw/pcb-defect-dataset/pcb-defect-dataset/val \
  --splits_root data/pcb/splits \
  --model yolov8n.pt \
  --imgsz 640 \
  --epochs 1 \
  --batch 8 \
  --conf 0.001 \
  --device 0 \
  --copy

!ls -R data/pcb/splits | head -n 40

!find data/raw/pcb-defect-dataset -type f -name "*.txt" | head -n 20

!find data/raw/pcb-defect-dataset -name "l_light_01_open_circuit_09_2_600.txt"

!ls data/raw/pcb-defect-dataset/pcb-defect-dataset/val

# Do these after your command runs
!ls -R data/pcb/splits | head -n 60       # should show images/train,val,test and labels/train,val,test
!ls data/pcb/splits/labels/train | head   # should list .txt files
!cat pcb.yaml                              # should point to data/pcb/splits/images/{train,val,test}

# list the first 20 label files from the training set
!find data/raw/pcb-defect-dataset -type f -path "*labels/*.txt" | head -n 20

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/5804/Intro-to-AI-Project

ROOT = "/content/drive/MyDrive/5804/Intro-to-AI-Project/data/raw/pcb-defect-dataset/pcb-defect-dataset/val/pcb-defect-dataset"

import os, yaml
cfg = {
    "path": ROOT,
    "train": os.path.join(ROOT, "train/images"),
    "val":   os.path.join(ROOT, "val/images"),
    "test":  os.path.join(ROOT, "test/images"),
    "nc": 6,
    "names": ["missing_hole","mouse_bite","open_circuit","short","spur","spurious_copper"],
}
with open("pcb_colab.yaml", "w") as f:
    yaml.safe_dump(cfg, f, sort_keys=False)

# sanity check the file
!sed -n '1,80p' pcb_colab.yaml

!find "$ROOT/train/labels" -type f -name "*.txt" | head -n 5
!find "$ROOT/val/labels"   -type f -name "*.txt" | head -n 5
!find "$ROOT/test/labels"  -type f -name "*.txt" | head -n 5

!pip install -U ultralytics==8.*

# quick smoke test
!yolo detect train model=yolov8n.pt data="pcb_colab.yaml" imgsz=640 epochs=1 batch=8 device=0 project=runs/detect name=baseline_smoke

!yolo detect train model=yolov8n.pt data="pcb_colab.yaml" imgsz=640 epochs=50 batch=16 device=0 project=runs/detect name=baseline_v1